[tool.poetry]
name = "curve-stablecoin"
version = "0.1.0"
description = ""
authors = ["Michael Egorov <michael@curve.fi>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
vyper = "0.3.7"
eth-abi = "5.0.1"
poetry = "1.4.1"


[tool.poetry.group.dev.dependencies]
brownie = "^0.5.1"
titanoboa = {git = "https://github.com/vyperlang/titanoboa.git", rev = "6ffcfa724023fb2b9f8ed02221c8bcbf4511712c"}
pycryptodome = "^3.19.1"
pytest = "^7.2.2"
hypothesis = "^6.70.1"
pdbpp = "^0.10.3"
jedi = "^0.18.2"
pytest-xdist = "^3.2.1"
pytest-forked = "^1.6.0"
ipython = "^8.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
